### ISSUE TITLE
[Bug]: tomllib throws error

### ISSUE THREAD

**Issue by wewewer123** [TurtleP/lovebrew#29]
### Software Version

0.7.0 (Latest)

### What Happened?

when running lovebrew.exe -i followed by lovebew.exe -b I get this output:"
Traceback (most recent call last):
  File "lovebrew\__main__.py", line 4, in <module>
  File "lovebrew\__init__.py", line 67, in main
  File "lovebrew\__init__.py", line 27, in build
  File "lovebrew\config.py", line 19, in __init__
  File "tomllib\_parser.py", line 66, in load
  File "tomllib\_parser.py", line 119, in loads
  File "tomllib\_parser.py", line 269, in skip_comment
  File "tomllib\_parser.py", line 259, in skip_until
tomllib.TOMLDecodeError: Found invalid character '\r' (at line 1, column 31)
[15848] Failed to execute script '__main__' due to unhandled exception!"

### What was Expected?

it's supposed to build (or atleast read the toml correctly)

### Operating System

Windows

### Operating System Version

Windows 10 19045.3448

### Code of Conduct

- [X] I have read the Code of Conduct and agree to these terms

**Comment by TurtleP** [comment]
This is no longer necessary, see the Wiki for updated instructions: https://lovebrew.org/#/lovebrew.md
